# Generated by Django 3.1.2 on 2020-11-03 22:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='date',
            field=models.CharField(default=datetime.datetime(2020, 11, 3, 22, 2, 30, 231270, tzinfo=utc), max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
